import type { BuilderComponentDefinition } from '../../builder/types';

export const moleculeComponents: BuilderComponentDefinition[] = [
  { type: 'Search', label: 'Search', layer: 'MOLECULE' },
  { type: 'Lookup', label: 'Lookup', layer: 'MOLECULE' },
  { type: 'SingleChoice', label: 'Single choice', layer: 'MOLECULE', description: 'Accept a single option' },
  { type: 'MultipleChoice', label: 'Multiple choice', layer: 'MOLECULE', description: 'Accept multiple options' },
  { type: 'DecisionBox', label: 'Decision box', layer: 'MOLECULE', description: 'When something needs to be accepted' },
  { type: 'SingleChoiceMatrix', label: 'Single choice matrix', layer: 'MOLECULE', description: 'Matrix of single choice options' },
  { type: 'MultipleChoiceMatrix', label: 'Multiple choice matrix', layer: 'MOLECULE', description: 'Matrix of multiple choice options' },
  { type: 'MatrixTable', label: 'Matrix table', layer: 'MOLECULE', description: 'Spreadsheet-like table of text inputs' },
  { type: 'Dropdown', label: 'Dropdown', layer: 'MOLECULE', description: 'Select input' },
  { type: 'Tags', label: 'Tags', layer: 'MOLECULE', description: 'Select multiple tags' },
  { type: 'ToggleSwitch', label: 'Toggle switch', layer: 'MOLECULE', description: 'Toggle / switch button' },
  { type: 'DateInput', label: 'Date', layer: 'MOLECULE', description: 'Datepicker input' },
  { type: 'TimeInput', label: 'Time', layer: 'MOLECULE', description: 'Time picker input' },
  { type: 'DateTimeInput', label: 'Date-time', layer: 'MOLECULE', description: 'Date & time picker input' },
  { type: 'MultipleDates', label: 'Multiple dates', layer: 'MOLECULE', description: 'Date picker that allows multiple dates' },
  { type: 'DateRange', label: 'Date range', layer: 'MOLECULE', description: 'Date picker that allows date range' },
  { type: 'Slider', label: 'Slider', layer: 'MOLECULE', description: 'Horizontal slider' },
  { type: 'RangeSlider', label: 'Range slider', layer: 'MOLECULE', description: 'Horizontal slider with range' },
  { type: 'UploadField', label: 'File upload', layer: 'MOLECULE', description: 'File upload input' },
  { type: 'ImageUpload', label: 'Image upload', layer: 'MOLECULE', description: 'File upload with image only' },
  { type: 'MultiFileUpload', label: 'Multi-file upload', layer: 'MOLECULE', description: 'Multi-file upload input' },
  { type: 'MultiImageUpload', label: 'Multi-image upload', layer: 'MOLECULE', description: 'Multi-file upload with images only' },
];
