export function VisualFirstMetadataDesigner() {
  return (
    <main className="redios-builder-page">
      <header className="redios-builder-topbar">
        <div>
          <span className="studio-kicker">Advanced Mode</span>
          <h1>Metadata Designer</h1>
          <p className="studio-muted">Technical view of the atomic metadata generated by RediOS Visual Builder.</p>
        </div>
        <button className="studio-chip" type="button" onClick={() => { window.location.href = '/studio'; }}>Back to Builder</button>
      </header>

      <section className="metadata-designer-page">
        <div className="redios-architecture-map">
          <strong>Metadata Designer</strong>
          <div className="redios-architecture-row">
            <span>DATA<br /><small>schema</small></span>
            <span>ACTION<br /><small>logic</small></span>
            <span>API<br /><small>runtime endpoint</small></span>
          </div>
        </div>

        <section className="metadata-designer-grid">
          <article className="studio-card">
            <span className="studio-kicker">DATA</span>
            <h3>Product Object</h3>
            <div className="studio-list">
              <div className="studio-list-row"><strong>name</strong><span>text</span></div>
              <div className="studio-list-row"><strong>stock</strong><span>number</span></div>
              <div className="studio-list-row"><strong>status</strong><span>dropdown</span></div>
            </div>
          </article>

          <article className="studio-card">
            <span className="studio-kicker">ACTION</span>
            <h3>Save Product Action</h3>
            <div className="studio-list">
              {['Validate', 'Save Object', 'Notify', 'Navigate'].map((step) => (
                <div key={step} className="studio-list-row"><strong>{step}</strong><span>event step</span></div>
              ))}
            </div>
          </article>

          <article className="studio-card">
            <span className="studio-kicker">API</span>
            <h3>Generated Runtime Capability</h3>
            <div className="studio-list">
              {['GET Product', 'POST Product', 'PUT Product', 'DELETE Product'].map((capability) => (
                <div key={capability} className="studio-list-row"><strong>{capability}</strong><span>generated</span></div>
              ))}
            </div>
          </article>
        </section>
      </section>
    </main>
  );
}
